# Generated by Django 5.0 on 2024-02-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_remove_flight_flight_class_remove_flight_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightclass',
            name='flight_id',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='FlightClass',
        ),
    ]
