# Generated by Django 5.0 on 2024-02-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_remove_flightclass_flight_id_delete_flight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('airline_name', models.TextField()),
                ('departure_city', models.TextField()),
                ('arrival_city', models.TextField()),
                ('departure_dateTime', models.DateTimeField()),
                ('arrival_dateTime', models.DateTimeField()),
                ('flight_trip', models.TextField()),
                ('price', models.IntegerField()),
                ('airline_image', models.ImageField(upload_to='uploads/images')),
            ],
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_class', models.TextField(choices=[('Business', 'Business')])),
                ('price', models.IntegerField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.flight')),
            ],
        ),
    ]
