# Generated by Django 5.0 on 2024-03-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0017_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_date',
            new_name='return_date',
        ),
    ]
