# Generated by Django 5.0 on 2024-03-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0019_flight_flight_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
