# Generated by Django 5.0 on 2024-02-14 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelRoomtype',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.TextField()),
                ('room_price', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.hotel')),
            ],
        ),
    ]
