# Generated by Django 5.0 on 2024-03-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0015_rename_arrival_date_flight_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightclass',
            name='flight_id',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='FlightClass',
        ),
    ]
