# Generated by Django 5.0 on 2024-03-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0020_delete_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('origin_code', models.CharField(max_length=200)),
                ('destination_code', models.CharField(max_length=200)),
                ('airline_name', models.TextField()),
                ('airplane_name', models.TextField()),
                ('departure_city', models.TextField()),
                ('arrival_city', models.TextField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('flight_trip', models.TextField()),
                ('flight_class', models.TextField()),
                ('price', models.IntegerField()),
                ('flight_duration', models.TextField(default=0)),
                ('airline_image', models.ImageField(upload_to='uploads/images')),
            ],
        ),
    ]
