# Generated by Django 5.0 on 2024-03-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0021_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtype',
            name='room_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resortroomtype',
            name='room_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
