# Generated by Django 5.0 on 2024-03-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightBooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubleflightreservations',
            name='username',
        ),
    ]
