# Generated by Django 5.0 on 2024-03-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightBooking', '0002_remove_doubleflightreservations_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundflightdetails',
            name='reservation_id',
        ),
        migrations.DeleteModel(
            name='InboundFlightDetails',
        ),
        migrations.DeleteModel(
            name='doubleFlightreservations',
        ),
        migrations.DeleteModel(
            name='OutboundFlightDetails',
        ),
    ]
