# Generated by Django 5.0 on 2024-02-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0004_alter_reservation_reservation_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
