# Generated by Django 5.0 on 2024-02-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
