# Generated by Django 5.0 on 2024-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_duration',
            field=models.IntegerField(default=0),
        ),
    ]
