# Generated by Django 5.0 on 2024-03-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0007_reservation_reservation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_duration',
            field=models.IntegerField(),
        ),
    ]
