# Generated by Django 5.0 on 2024-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0008_alter_reservation_reservation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_location',
            field=models.CharField(default='ras', max_length=400),
        ),
    ]
