# Generated by Django 5.0 on 2024-03-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0009_reservation_reservation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_location',
            field=models.CharField(max_length=400),
        ),
    ]
