# Generated by Django 5.0 on 2024-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBooking', '0006_doubleflightreservations_inboundflightdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleflightreservations',
            name='destination_code',
            field=models.CharField(default='s', max_length=20),
        ),
        migrations.AddField(
            model_name='doubleflightreservations',
            name='origin_code',
            field=models.CharField(default='s', max_length=20),
        ),
        migrations.AddField(
            model_name='doubleflightreservations',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
