# Generated by Django 5.0 on 2024-03-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightBooking', '0007_doubleflightreservations_destination_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleflightreservations',
            name='destination_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doubleflightreservations',
            name='origin_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doubleflightreservations',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
